### ISSUE TITLE
How to change rtplibrary1.5.0 to rtplibrary1.9.3

### ISSUE THREAD

**Issue by hbbdzry** [pedroSG94/Stream-USB-test#5]
After I upgraded, it showed no import com.pedro.encoder.input.video.Frame；
rtsp-server-master change rtplibrary1.9.3 to rtplibrary1.5.0 ，it's wrong。
How to change it is correct

**Comment by pedroSG94** [comment]
Frame class import changed from com.pedro.encoder.input.video.Frame to com.pedro.encoder.Frame

**Comment by hbbdzry** [comment]
thank you，I now invoke this function : public void stopRecord(UVCCamera uvcCamera)，The following error was obtained

Process: com.sobest.sobestendoscope, PID: 17569
    java.lang.IllegalStateException: Failed to stop the muxer
        at android.media.MediaMuxer.nativeStop(Native Method)
        at android.media.MediaMuxer.stop(MediaMuxer.java:454)
        at com.sobest.sobestendoscope.server.USBBase.stopRecord(USBBase.java:219)
        at com.sobest.sobestendoscope.MainActivity.onClick(MainActivity.kt:508)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25902)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:951)

**Comment by Allan-Nava** [comment]
News?
